# Generated by Django 5.0.1 on 2024-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='texto', max_length=200),
        ),
    ]
