# Generated by Django 5.0.1 on 2024-01-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_app', '0002_topic_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_app.topic')),
            ],
        ),
    ]
